@startuml FamilyTree
skinparam component {
	backgroundColor<<Male>> Orange
	backgroundColor<<Female>> Yellow
}

'Babas Side List
[Rumi Kha]<<Male>>#red

[Mohammed Joma]<<Male>>#red
[Jongiy Mohammed]<<Male>>#red
[Mohammed Rafi]<<Male>>#red

[Sadok Mohammed]<<Male>>#red
[Innat Mohammed]<<Male>>#red
[Ashrof Mohammed]<<Male>>#red
[Rojob Uddin]<<Male>>#red
[Ajimuddin]<<Male>>#red

[Golam Mohammed]<<Male>>#red
[Jamal Mohammed]<<Male>>#red
[Jori Mohammed]<<Male>>#red
[Mohammed Ashrof]<<Male>>#red

[Abdul Ali]<<Male>>#red
[Hafiz Ajfor Ali]<<Male>>#red
[Mokluja Bibi]<<Female>>#red


[Mosharof Hussain]<<Male>>#red
[Rehana Khatun]<<Female>>

[Monzoor Murshed]<<Male>>
[Israt Jahan]<<Female>>

[Mahbub Murshed]<<Male>>
[Shamsunna Borat Chowdhury]<<Female>>

[Maksud Murshed]<<Male>>
[Mahmuda Begum]<<Female>>

[Minhaz Murshed]<<Male>>
[Ruby Chachi]<<Female>>

[Mahtab Murshed]<<Male>>
[Fateha Chachi]<<Female>>

[Razi Murshed]<<Male>>
[Wazih Abbas Murshed]<<Male>>
[Rafid Murshed]<<Male>>
[Sadid Murshed]<<Male>>
[Mariam Murshed]<<Female>>
[Siam Murshed]<<Male>>
[Ilham Murshed]<<Male>>
[Musa Murshed]<<Male>>
[Mahdi Murshed]<<Male>>
[Moaz Murshed]<<Male>>
[Tasnim Murshed]<<Female>>
[Tohfa Murshed]<<Female>>
[Tabassum Murshed]<<Female>>

'Ma's Side List
[Taiyeb Ali]<<Male>>#red
[Shah Saleha Begum]<<Female>>#red

[Ataur Rahman]<<Male>>#red
[Rownak Jahan]<<Female>>
[Mujibur Rahman]<<Male>>
[Rowshan Jahan]<<Female>>
[Ahmed Abu Saleh]<<Male>>
[Noor Jahan]<<Female>>
[Abul Fateh M Abdullah]<<Male>>
[Aditi Titas Huq]<<Female>>

[Anwar Sadmani]<<Male>>
[Shapla Sadmani]<<Female>>
[Fatima Al Zahra]<<Female>>

[Shahriar Rahman]<<Male>>
[Hajera Akhter]<<Female>>
[Ayesha Ayana]<<Female>>
[Ayham Abdullah]<<Male>>

[Akmar Saminur Rahman]<<Male>>
[Nahiyan Rahman]<<Male>>#red

[Akif Sadeed]<<Male>>
[Farina Mahrin]<<Female>>

[Rushnan Anusha]<<Female>>
[Rashad Arbab]<<Male>>

'Ma's Side Begin
[Taiyeb Ali]----right-[Shah Saleha Begum]
    [Taiyeb Ali]-[#red]---->[Israt Jahan]
    [Shah Saleha Begum]-[#blue]---->[Israt Jahan]
    [Taiyeb Ali]-[#red]->[Rownak Jahan]
    [Shah Saleha Begum]-[#blue]->[Rownak Jahan]
    [Taiyeb Ali]-[#red]-->[Rowshan Jahan]
    [Shah Saleha Begum]-[#blue]-->[Rowshan Jahan]
    [Taiyeb Ali]-[#red]--->[Noor Jahan]
    [Shah Saleha Begum]-[#blue]--->[Noor Jahan]
    [Taiyeb Ali]-[#red]----->[Abul Fateh M Abdullah]
    [Shah Saleha Begum]-[#blue]----->[Abul Fateh M Abdullah]

    'Bokkhanu
    [Rownak Jahan]----right-[Ataur Rahman]
        [Ataur Rahman]-[#red]->[Anwar Sadmani]
        [Rownak Jahan]-[#blue]->[Anwar Sadmani]
        [Ataur Rahman]-[#red]-->[Shahriar Rahman]
        [Rownak Jahan]-[#blue]-->[Shahriar Rahman]

        'Ashek Bhaia
            [Anwar Sadmani]----right-[Shapla Sadmani]
                [Anwar Sadmani]-[#red]->[Fatima Al Zahra]
                [Shapla Sadmani]-[#blue]->[Fatima Al Zahra]

        'Arif Bhaia
        [Shahriar Rahman]----right-[Hajera Akhter]
            [Shahriar Rahman]-[#red]->[Ayham Abdullah]
            [Hajera Akhter]-[#blue]->[Ayham Abdullah]
            [Shahriar Rahman]-[#red]-->[Ayesha Ayana]
            [Hajera Akhter]-[#blue]-->[Ayesha Ayana]

    'Majpa Khala
    [Rowshan Jahan]----right-[Mujibur Rahman]
        [Mujibur Rahman]-[#red]-->[Akmar Saminur Rahman]
        [Rowshan Jahan]-[#blue]-->[Akmar Saminur Rahman]
        [Mujibur Rahman]-[#red]->[Nahiyan Rahman]
        [Rowshan Jahan]-[#blue]->[Nahiyan Rahman]

    'Duduma Khala
    [Noor Jahan]----right-[Ahmed Abu Saleh]
        [Ahmed Abu Saleh]-[#red]->[Akif Sadeed]
        [Noor Jahan]-[#blue]->[Akif Sadeed]
        [Ahmed Abu Saleh]-[#red]-->[Farina Mahrin]
        [Noor Jahan]-[#blue]-->[Farina Mahrin]

    'Mamu
    [Abul Fateh M Abdullah]----right-[Aditi Titas Huq]
        [Abul Fateh M Abdullah]-[#red]->[Rushnan Anusha]
        [Aditi Titas Huq]-[#blue]->[Rushnan Anusha]
        [Abul Fateh M Abdullah]-[#red]->[Rashad Arbab]
        [Aditi Titas Huq]-[#blue]->[Rashad Arbab]

' Babas Side Begin

[Rumi Kha]-[#red]->[Mohammed Joma]
[Rumi Kha]-[#red]->[Jongiy Mohammed]
[Rumi Kha]-[#red]->[Mohammed Rafi]

[Jongiy Mohammed]-[#red]->[Sadok Mohammed]
[Jongiy Mohammed]-[#red]-[Innat Mohammed]
[Jongiy Mohammed]-[#red]-[Ashrof Mohammed]
[Jongiy Mohammed]-[#red]-[Rojob Uddin]
[Jongiy Mohammed]-[#red]-[Ajimuddin]

[Innat Mohammed]-[#red]->[Golam Mohammed]
[Innat Mohammed]-[#red]->[Jamal Mohammed]
[Innat Mohammed]-[#red]->[Jori Mohammed]
[Innat Mohammed]-[#red]->[Mohammed Ashrof]

[Abdul Ali]<<Male>>#red
[Hafiz Ajfor Ali]<<Male>>#red
[Mokluja Bibi]<<Female>>#red

[Jori Mohammed]-[#red]->[Abdul Ali]
[Jori Mohammed]-[#red]->[Hafiz Ajfor Ali]

[Mohammed Ashrof]-[#red]->[Mokluja Bibi]

[Abdul Ali]----right-[Mokluja Bibi]
    [Mokluja Bibi]-[#blue]->[Mosharof Hussain]
    [Abdul Ali]-[#red]->[Mosharof Hussain]

[Mosharof Hussain]----right-[Rehana Khatun]
    [Rehana Khatun]-[#blue]->[Monzoor Murshed]
    [Mosharof Hussain]-[#red]->[Monzoor Murshed]
    [Rehana Khatun]-[#blue]-->[Mahbub Murshed]
    [Mosharof Hussain]-[#red]-->[Mahbub Murshed]
    [Rehana Khatun]-[#blue]--->[Maksud Murshed]
    [Mosharof Hussain]-[#red]--->[Maksud Murshed]
    [Rehana Khatun]-[#blue]---->[Minhaz Murshed]
    [Mosharof Hussain]-[#red]---->[Minhaz Murshed]
    [Rehana Khatun]-[#blue]---->[Mahtab Murshed]
    [Mosharof Hussain]-[#red]---->[Mahtab Murshed]

    [Monzoor Murshed]----right-[Israt Jahan]
        [Monzoor Murshed]-[#red]->[Razi Murshed]
        [Israt Jahan]-[#blue]->[Razi Murshed]
        [Monzoor Murshed]-[#red]-->[Wazih Abbas Murshed]
        [Israt Jahan]-[#blue]-->[Wazih Abbas Murshed]

    [Mahbub Murshed]----right-[Shamsunna Borat Chowdhury]
        [Mahbub Murshed]-[#red]->[Rafid Murshed]
        [Shamsunna Borat Chowdhury]-[#blue]->[Rafid Murshed]
        [Mahbub Murshed]-[#red]-->[Sadid Murshed]
        [Shamsunna Borat Chowdhury]-[#blue]-->[Sadid Murshed]
        [Mahbub Murshed]-[#red]--->[Mariam Murshed]
        [Shamsunna Borat Chowdhury]-[#blue]--->[Mariam Murshed]

    [Maksud Murshed]----right-[Mahmuda Begum]
        [Maksud Murshed]-[#red]->[Siam Murshed]
        [Mahmuda Begum]-[#blue]->[Siam Murshed]
        [Maksud Murshed]-[#red]-->[Ilham Murshed]
        [Mahmuda Begum]-[#blue]-->[Ilham Murshed]

    [Minhaz Murshed]----right-[Ruby Chachi]
        [Minhaz Murshed]-[#red]->[Musa Murshed]
        [Ruby Chachi]-[#blue]->[Musa Murshed]
        [Minhaz Murshed]-[#red]-->[Mahdi Murshed]
        [Ruby Chachi]-[#blue]-->[Mahdi Murshed]
        [Minhaz Murshed]-[#red]--->[Moaz Murshed]
        [Ruby Chachi]-[#blue]--->[Moaz Murshed]

    [Mahtab Murshed]----right-[Fateha Chachi]
        [Mahtab Murshed]-[#red]->[Tasnim Murshed]
        [Fateha Chachi]-[#blue]->[Tasnim Murshed]
        [Mahtab Murshed]-[#red]-->[Tohfa Murshed]
        [Fateha Chachi]-[#blue]-->[Tohfa Murshed]
        [Mahtab Murshed]-[#red]--->[Tabassum Murshed]
        [Fateha Chachi]-[#blue]--->[Tabassum Murshed]
' Babas Side End

@enduml
